services:
  - type: web
    name: timemaster
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: timemaster-db
          property: connectionString
databases:
  - name: timemaster-db
    databaseName: timemaster
    user: timemaster
